### ISSUE TITLE
bug: can't run on M1 Pro MacOS Sonoma 14.3.1

### ISSUE THREAD

**Issue by Korayem** [LlamaEdge/LlamaEdge#153]
### Summary

Can't run on Macbook

### Reproduction steps

I followed the instructions and ran `bash <(curl -sSfL 'https://raw.githubusercontent.com/LlamaEdge/LlamaEdge/main/run-llm.sh') --model llama-3-8b-instruct` and got an error

### Screenshots

![DESCRIPTION](LINK.png)

### Any logs you want to share for showing the specific issue

```
[+] Extracting prompt type: llama-3-chat 
[+] No reverse prompt required
[+] Install WasmEdge with wasi-nn_ggml plugin ...

Using Python: /Library/Frameworks/Python.framework/Versions/3.12/bin/python3 
<stdin>:250: SyntaxWarning: invalid escape sequence '\d'
<stdin>:1370: SyntaxWarning: invalid escape sequence '\+'
INFO    - CUDA is only supported on Linux
INFO    - CUDA is only supported on Linux
WARNING - Experimental Option Selected: plugins
WARNING - plugins option may change later
INFO    - Compatible with current configuration
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/urllib/request.py", line 1344, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/http/client.py", line 1331, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/http/client.py", line 1377, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/http/client.py", line 1326, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/http/client.py", line 1085, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/http/client.py", line 1029, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/http/client.py", line 1472, in connect
    self.sock = self._context.wrap_socket(self.sock,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/ssl.py", line 455, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/ssl.py", line 1042, in _create
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/ssl.py", line 1320, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1896, in <module>
  File "<stdin>", line 1609, in main
  File "<stdin>", line 44, in wrap_download_url
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/urllib/request.py", line 240, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
                            ^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/urllib/request.py", line 215, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/urllib/request.py", line 515, in open
    response = self._open(req, data)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/urllib/request.py", line 532, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/urllib/request.py", line 492, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/urllib/request.py", line 1392, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/urllib/request.py", line 1347, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)>
Failed to install WasmEdge
```

### Model Information

Meta-Llama-3-8B-Instruct-Q5_K_M.gguf

### Operating system information

MacOS Sonoma 14.3.1

### ARCH

arm64

### CPU Information

Apple M1 Pro

### Memory Size

16GB

### GPU Information

Apple M1 Pro

### VRAM Size

5461MB

**Comment by alabulei1** [comment]
Hi  @Korayem 

This problem can be reproduced. You can solve your problem by upgrading python version on your macOS.

We're going to remove the python dependency when installing WasmEdge in the upcoming days. Stay tuned!

**Comment by gnodabb** [comment]
What version of python fixes this. I upgraded to Python 3.12.3 and still have the same error.

**Comment by hydai** [comment]
@Korayem 
I am afraid that the macOS update breaks the Python certifi package.

Here are some fixes you may want to try:
1. https://stackoverflow.com/questions/40684543/how-to-make-python-use-ca-certificates-from-mac-os-truststore/57795811#57795811
2. https://github.com/python/cpython/blob/main/Mac/BuildScript/resources/install_certificates.command

**Comment by ChristianWeyer** [comment]
> Hi @Korayem
> 
> This problem can be reproduced. You can solve your problem by upgrading python version on your macOS.
> 
> We're going to remove the python dependency when installing WasmEdge in the upcoming days. Stay tuned!

Do you have an ETA when the Python dependency will be removed?

**Comment by hydai** [comment]
Hi @ChristianWeyer 
You can use the installer v2: https://github.com/WasmEdge/WasmEdge/blob/master/utils/install_v2.sh
No more python deps.
